# Generated by Django 4.2 on 2023-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
